[build]
  command = "npm install"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/express"
  status = 200

[functions.express]
  included_files = "views/**"
