[build]
  # Install dependencies (Netlify will run this automatically)
  command = "npm install"
  # You can leave the publish directory empty if your app is fully serverless
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/express"
  status = 200
